import WEBSITE_LINKS from "./website-links";
import { WebsiteNavigationConfig } from "../types/navigation-types";
import { House, Shield } from "lucide-react";
import { todayLocalYMD } from "~/domain/kds";

const ADMIN_NAVIGATION_LINKS: WebsiteNavigationConfig = {
  mainNav: [WEBSITE_LINKS.admin, WEBSITE_LINKS.website],
  sidebarNav: [
    {
      title: "Fixados",
      items: [
        {
          title: "Pagina Inicial",
          href: "/admin",
          items: [],
          disabled: false,
          highlight: true,
          icon: House,
          tags: ["home", "inicio", "dashboard", "painel", "principal"],
        },
        {
          title: "Website",
          href: "/",
          items: [],
          disabled: true,
          tags: ["site", "publico", "cliente", "loja"],
        },
      ],
    },
    {
      title: "Atendimento",
      items: [
        {
          title: "KDS",
          href: "/admin/kds/atendimento",
          items: [],
          disabled: false,
          tags: ["kitchen display", "tela cozinha", "display", "producao", "atendimento"],
        },
        {
          title: "Horários de atendimento",
          href: "/admin/atendimento/horarios",
          items: [],
          disabled: false,
          tags: ["horas", "funcionamento", "abertura", "fechamento", "horario", "turno"],
        },
        {
          title: "Lista de sabores",
          href: "/admin/atendimento/lista-sabores",
          items: [],
          disabled: false,
          tags: ["sabores", "pizza", "lista", "flavors", "opcoes"],
        },
        {
          title: "Assistente de Escolha",
          href: "/admin/atendimento/assistente-de-escolha",
          items: [],
          disabled: false,
          tags: ["ajuda escolha", "recomendacao", "sugestao", "flavors", "assistente"],
        },

        {
          title: "Pedidos",
          href: "/admin/daily-orders",
          items: [],
          disabled: false,
          tags: ["orders", "diario", "pedido", "venda", "diarios"],
        },
        {
          title: "Linha do tempo Pedidos",
          href: "/admin/orders-delays-timeline-segmentation",
          items: [],
          disabled: true,
          tags: ["timeline", "atraso", "segmentacao", "pedidos", "tempo"],
        },
        {
          title: "Linha do tempo Entrega",
          href: "/admin/orders-delivery-time-left",
          items: [],
          disabled: false,
          tags: ["entrega", "delivery", "tempo", "prazo", "timeline"],
        },
        {
          title: "Comentarios clientes",
          href: "/admin/atendimento/comentarios",
          items: [],
          disabled: false,
          tags: ["feedback", "avaliacao", "review", "opiniao", "cliente", "nota"],
        },
      ],
    },
    {
      title: "Vendas",
      items: [
        {
          title: "Itens vendidos",
          href: "/admin/vendas/itens-vendidos",
          items: [],
          disabled: false,
          tags: ["sales", "relatorio", "vendas", "historico", "estatisticas", "resultados"],
        },
        {
          title: "Canais de venda",
          href: "/admin/canais-venda",
          items: [],
          disabled: false,
          tags: ["ifood", "delivery", "canal", "plataforma", "marketplace"],
        },
        {
          title: "Cardápio",
          href: "",
          items: [
            {
              title: "Cardápio Delivery",
              href: "/admin/gerenciamento/cardapio/main/list",
              items: [],
              disabled: false,
              tags: ["menu", "delivery", "items", "precos", "cardapio", "lista"],
            },
            {
              title: "Cardápio Pizza Al Taglio",
              href: "/admin/gerenciamento/cardapio-pizza-al-taglio",
              items: [],
              disabled: false,
              tags: ["taglio", "pizza", "fatia", "balcao", "cardapio"],
            },
            {
              title: "Grupos",
              href: "/admin/gerenciamento/cardapio/groups",
              items: [],
              disabled: false,
              tags: ["grupo", "categoria", "cardapio", "classificacao", "secao"],
            },
            {
              title: "Tamanhos",
              href: "/admin/gerenciamento/cardapio/sizes",
              items: [],
              disabled: false,
              tags: ["size", "tamanho", "porcao", "grande", "pequeno", "medio"],
            },
          ],
          disabled: false,
          tags: ["cardapio", "menu", "delivery", "pizza"],
        },
        {
          title: "Comercial",
          href: "",
          items: [
            {
              title: "Preços de venda",
              href: "/admin/gerenciamento/cardapio/sell-price-management/cardapio/edit-items",
              items: [],
              disabled: false,
              tags: ["preco", "valor", "tabela", "comercial", "venda"],
            },
            {
              title: "Preços de venda (Novo)",
              href: "/admin/vendas/sell-price-management",
              items: [],
              disabled: false,
              tags: ["preco novo", "valor", "tabela", "comercial", "venda"],
            },
            {
              title: "DNA",
              href: "/admin/vendas/dna",
              items: [],
              disabled: false,
              tags: ["perfil", "identidade", "marca", "posicionamento", "diferencial"],
            },
          ],
          disabled: false,
          tags: ["comercial", "preco", "valor", "vendas"],
        },
        {
          title: "Relatorios",
          href: "",
          items: [
            {
              title: "Visitas",
              href: "/admin/gerenciamento/cardapio/dashboard/visitas",
              items: [],
              disabled: false,
              tags: ["acesso", "pageview", "visualizacao", "analytics", "trafego"],
            },
            {
              title: "Dashboard de Interesse",
              href: "/admin/gerenciamento/cardapio/dashboard/tracking",
              items: [],
              disabled: false,
              tags: ["interesse", "tracking", "engajamento", "analytics", "comportamento"],
            },
            {
              title: "Menu Engineering Matrix",
              href: "/admin/gerenciamento/cardapio/dashboard/menu-engineering",
              items: [],
              disabled: false,
              tags: ["matrix", "engenharia", "lucratividade", "popularidade", "analise"],
            },
          ],
          disabled: false,
          tags: ["relatorio", "dashboard", "analise", "vendas"],
        },

        {
          title: "Ferramentas",
          href: "",
          items: [
            {
              title: "Publicados sem ficha",
              href: "/admin/vendas/publicados-sem-ficha",
              items: [],
              disabled: false,
              tags: ["auditoria", "incompleto", "ficha", "custo", "publicado"],
            },
            {
              title: "Combos",
              href: "/admin/vendas/combos",
              items: [],
              disabled: false,
              tags: ["combo", "promocao", "conjunto", "pacote", "kit"],
            },
            {
              title: "Análise cardápio concorrência",
              href: "/admin/vendas/analise-cardapio-concorrencia/pesquisar/resultados",
              items: [],
              disabled: false,
              tags: ["concorrencia", "aiqfome", "ingrediente", "preco", "mercado", "cardapio"],
            },
            {
              title: "Promo 'Fotos Cardapio'",
              href: "/admin/gerenciamento/pizza-promo",
              items: [],
              disabled: false,
              tags: ["foto", "imagem", "promocao", "promo", "pizza"],
            },
            {
              title: "Vínculo assets (lote)",
              href: "/admin/gerenciamento/cardapio/assets-batch",
              items: [],
              disabled: false,
              tags: ["asset", "imagem", "lote", "vinculo", "bulk"],
            },
          ],
          disabled: false,
          tags: ["ferramentas", "utilitarios", "vendas"],
        },
      ],
    },
    {
      title: "Custos e Margem",
      items: [
        {
          title: "Fornecedores",
          href: "/admin/suppliers",
          items: [],
          disabled: false,
          tags: ["supplier", "compra", "insumo", "parceiro", "fornecedor"],
        },
        {
          title: "Fichas de custo",
          href: "/admin/item-cost-sheets",
          items: [],
          disabled: false,
          tags: ["ficha tecnica", "recipe", "custo", "ingrediente", "composicao"],
        },
        {
          title: "Monitoramento",
          href: "",
          items: [
            {
              title: "Consulta de custo",
              href: "/admin/cost-monitoring",
              items: [],
              disabled: false,
              tags: ["consulta", "custo", "preco", "insumo", "pesquisa"],
            },
            {
              title: "Impacto de custos",
              href: "/admin/cost-impact",
              items: [],
              disabled: false,
              tags: ["impacto", "variacao", "margem", "analise", "sensibilidade"],
            },
            {
              title: "Histórico global de custos",
              href: "/admin/global-cost-history",
              items: [],
              disabled: false,
              tags: ["historico", "custo", "evolucao", "passado", "tendencia"],
            },
          ],
          disabled: false,
          tags: ["monitoramento", "custo", "margem", "analise"],
        },
        {
          title: "Ferramentas",
          href: "",
          items: [
            {
              title: "Recalcular fichas técnicas",
              href: "/admin/recalculate-item-cost-sheets",
              items: [],
              disabled: false,
              tags: ["recalculo", "atualizar", "ficha", "custo", "sincronizar"],
            },
            {
              title: "Recalcular custos itens",
              href: "/admin/recalculate-costs",
              items: [],
              disabled: false,
              tags: ["recalculo", "atualizar", "item", "custo", "sincronizar"],
            },
            {
              title: "Editar fichas em lote",
              href: "/admin/item-cost-sheets-batch",
              items: [],
              disabled: false,
              tags: ["lote", "bulk", "ficha", "editar", "massa"],
            },
          ],
          disabled: false,
          tags: ["ferramentas", "recalculo", "custo"],
        },
        {
          title: "Comercial",
          href: "",
          items: [
            {
              title: "Custo cardápio",
              href: "/admin/gerenciamento/cardapio/cost-management",
              items: [],
              disabled: false,
              tags: ["custo", "cardapio", "margem", "preco", "lucratividade"],
            },
          ],
          disabled: false,
          tags: ["comercial", "custo", "margem"],
        },
      ],
    },
    {
      title: "Estoque",
      items: [
        {
          title: "Itens",
          href: "/admin/items",
          items: [],
          disabled: false,
          tags: ["item", "ingrediente", "produto", "insumo", "materia prima"],
        },
        {
          title: "Movimentações de estoque",
          href: "/admin/stock-movements",
          items: [],
          disabled: false,
          tags: ["movimento", "entrada", "saida", "estoque", "transacao"],
        },
        {
          title: "Relatorios",
          href: "",
          items: [
            {
              title: "Por Fornecedor",
              href: "/admin/estoque/relatorio/por-fornecedor",
              items: [],
              disabled: false,
              tags: ["fornecedor", "relatorio", "compra", "estoque", "analise"],
            },
            {
              title: "Frete por Fornecedor",
              href: "/admin/estoque/relatorio/frete-fornecedor",
              items: [],
              disabled: false,
              tags: ["frete", "transporte", "fornecedor", "logistica", "custo entrega"],
            },
            {
              title: "Aprovações de custo",
              href: "/admin/import-stock-movements/cost-review-approvals",
              items: [],
              disabled: false,
              tags: ["aprovacao", "custo", "revisao", "validacao", "conferencia"],
            },
          ],
          disabled: false,
          tags: ["relatorio", "estoque", "analise"],
        },
        {
          title: "Ferramentas",
          href: "",
          items: [
            {
              title: "Importação de movimentações",
              href: "/admin/import-stock-movements",
              items: [],
              disabled: false,
              tags: ["importar", "upload", "csv", "movimentacao", "entrada"],
            },
            {
              title: "Aliases de Importação",
              href: "/admin/item-import-aliases",
              items: [],
              disabled: false,
              tags: ["alias", "nome", "sinonimo", "importacao", "mapeamento"],
            },
            {
              title: "Conciliação de fornecedor",
              href: "/admin/supplier-reconciliation",
              items: [],
              disabled: false,
              tags: ["conciliacao", "reconciliacao", "fornecedor", "conferencia", "auditoria"],
            },
          ],
          disabled: false,
          tags: ["ferramentas", "importacao", "estoque"],
        },
      ],
    },
    {
      title: "Produção",
      items: [
        {
          title: "Estoque de massa",
          href: `/admin/kds/atendimento/${todayLocalYMD()}/estoque-massa`,
          items: [],
          disabled: false,
          tags: ["massa", "pizza", "producao", "dough", "estoque"],
        },
        {
          title: "Programação Diaria",
          href: "/admin/producao/programacao-diaria",
          items: [],
          disabled: false,
          tags: ["producao", "diario", "agenda", "planejamento", "programacao"],
        },
        {
          title: "Receitas",
          href: "/admin/recipes",
          items: [],
          disabled: false,
          tags: ["recipe", "ficha", "ingrediente", "preparo", "modo de fazer"],
        },
        {
          title: "Ferramentas",
          href: "",
          items: [
            {
              title: "Publicados sem receita",
              href: "/admin/producao/publicados-sem-receita",
              items: [],
              disabled: false,
              tags: ["auditoria", "incompleto", "receita", "producao", "publicado"],
            },
            {
              title: "Ingredientes por sabores",
              href: "/admin/vendas/ingredientes-sabores",
              items: [],
              disabled: false,
              tags: ["ingrediente", "sabor", "composicao", "alergenico", "componente"],
            },
          ],
          disabled: false,
          tags: ["ferramentas", "producao", "receita"],
        },
      ],
    },
    {
      title: "Financeiro",
      items: [
        {
          title: "Metas financeiras",
          href: "/admin/financeiro/metas",
          items: [],
          disabled: false,
          tags: ["meta", "objetivo", "target", "financeiro", "resultado"],
        },
        {
          title: "Fechamento mensal",
          href: "/admin/financeiro/fechamento-mensal",
          items: [],
          disabled: false,
          tags: ["fechamento", "mes", "relatorio", "financeiro", "balanco"],
        },

        {
          title: "Importador",
          href: "/admin/financeiro/importer",
          items: [],
          disabled: false,
          tags: ["importar", "dados", "financeiro", "upload", "planilha"],
        },
      ],
    },
    {
      title: "Cadastro",
      items: [
        {
          title: "Variações",
          href: "/admin/variations",
          items: [],
          disabled: false,
          tags: ["variacao", "opcao", "personalizar", "adicional", "complemento"],
        },
        {
          title: "Categorias",
          href: "/admin/categorias",
          items: [],
          disabled: false,
          tags: ["categoria", "grupo", "classificacao", "tipo", "secao"],
        },
        {
          title: "Unidades de consumo",
          href: "/admin/unidades-consumo",
          items: [],
          disabled: false,
          tags: ["unidade", "medida", "kg", "litro", "grama", "ml"],
        },

        {
          title: "Opções",
          href: "/admin/options",
          items: [],
          disabled: true,
          tags: ["opcao", "adicional", "customizacao", "complemento", "extra"],
        },
      ],
    },
    {
      title: "Cozinha",
      items: [
        {
          title: "KDS",
          href: "/admin/kds/cozinha",
          items: [],
          disabled: false,
          tags: ["kitchen display", "cozinha", "display", "tela", "pedido"],
        },
        {
          title: "Lista de compras",
          href: "/admin/grocery-shopping-list",
          items: [],
          disabled: false,
          tags: ["compra", "shopping", "ingrediente", "lista", "mercado"],
        },
        {
          title: "Massa",
          href: "/admin/dough",
          items: [],
          disabled: false,
          tags: ["dough", "massa", "pizza", "producao", "fermentacao"],
        },

        {
          title: "Pizza Al Taglio",
          href: "/admin/pizza-al-taglio",
          items: [],
          disabled: false,
          tags: ["taglio", "pizza", "fatia", "balcao", "cozinha"],
        },
      ],
    },
    {
      title: "RH",
      items: [
        {
          title: "Lista de vagas",
          href: "/admin/hr/job-openings",
          items: [],
          disabled: false,
          tags: ["vaga", "emprego", "contratacao", "recrutamento", "posicao"],
        },
        {
          title: "Lista de candidaturas recebidas",
          href: "/admin/hr/applications",
          items: [],
          disabled: false,
          tags: ["candidato", "curriculo", "aplicacao", "selecao", "candidatura"],
        },
        {
          title: "Analise candidatos 'Auxiliar Cozinha'",
          href: "/admin/hr/analise/auxiliar-cozinha",
          items: [],
          disabled: false,
          tags: ["auxiliar", "cozinha", "analise", "candidato", "selecao"],
        },
      ],
    },
    {
      title: "BOT",
      disabled: false,
      items: [
        {
          title: "Debug page",
          href: "/admin/wpp",
          items: [],
          disabled: false,
          tags: ["debug", "teste", "whatsapp", "wpp", "log"],
        },
        {
          title: "Auto Responder",
          href: "/admin/bot/auto-responder",
          items: [],
          disabled: false,
          tags: ["resposta automatica", "bot", "whatsapp", "mensagem", "automatico"],
        },
        {
          title: "Configurar Auto Responder",
          href: "/admin/bot/auto-responder/settings",
          items: [],
          disabled: false,
          tags: ["configuracao", "bot", "resposta", "regra", "whatsapp"],
        },
        {
          title: "META Autoresponder",
          href: "/admin/bot/meta-auto-responder",
          items: [],
          disabled: false,
          tags: ["meta", "facebook", "instagram", "autoresponder", "bot"],
        },
        {
          title: "NLP",
          href: "/admin/nlp",
          items: [],
          disabled: false,
          tags: ["linguagem natural", "inteligencia artificial", "processamento", "texto", "ia"],
        },
      ],
    },
    {
      title: "Clientes Inativos",
      disabled: false,
      items: [
        {
          title: "(1) Importar base clientes",
          href: "/admin/importer/new/csv",
          items: [],
          disabled: false,
          tags: ["importar", "csv", "cliente", "base", "upload"],
        },
        {
          title: "(3) Consolidar clientes",
          href: "/admin/clientes-inativos/consolidar-cliente",
          items: [],
          disabled: false,
          tags: ["consolidar", "clientes", "inativos", "base", "unificar"],
        },
        {
          title: "Campanhas",
          href: "/admin/clientes-inativos/manual",
          items: [],
          disabled: false,
          tags: ["campanha", "marketing", "comunicacao", "clientes inativos", "reativacao"],
        },
      ],
    },
    {
      title: "Administração",
      disabled: false,
      items: [
        {
          title: "Configurações globais",
          href: "/admin/administracao/settings",
          items: [],
          disabled: false,
          tags: ["configuracao", "sistema", "global", "admin", "parametros"],
        },
        {
          title: "AI Context Profile",
          href: "/admin/administracao/ai-context-profile",
          items: [],
          disabled: false,
          tags: ["ai", "inteligencia artificial", "perfil", "contexto", "ia"],
        },
        {
          title: "Usuários",
          href: "/admin/users",
          items: [],
          disabled: false,
          tags: ["usuario", "acesso", "login", "permissao", "conta"],
        },
        {
          title: "Sessões",
          href: "/admin/sessions",
          items: [],
          disabled: false,
          tags: ["sessao", "login", "acesso", "ativo", "autenticacao"],
        },
        {
          title: "Importador de dados",
          href: "/admin/importer",
          items: [],
          disabled: false,
          tags: ["importar", "dados", "migracao", "upload", "csv"],
        },
        {
          title: "Gerenciamento de assets",
          href: "/admin/assets",
          items: [],
          disabled: false,
          tags: ["asset", "imagem", "arquivo", "midia", "foto"],
        },
        {
          title: "Backup do banco",
          href: "/admin/database-backup",
          items: [],
          disabled: false,
          tags: ["backup", "banco de dados", "seguranca", "restore", "exportar"],
        },

        {
          title: "Zone de entrega",
          href: "/admin/delivery-zone",
          items: [],
          disabled: false,
          tags: ["zona", "entrega", "delivery", "area", "bairro"],
        },
        {
          title: "Zone de entrega - Distançias",
          href: "/admin/delivery-zone-distance",
          items: [],
          disabled: false,
          tags: ["distancia", "raio", "entrega", "km", "area"],
        },
        {
          title: "Z-API Contatos",
          href: "/admin/zapi/contacts",
          items: [],
          disabled: false,
          tags: ["zapi", "whatsapp", "contato", "api", "agenda"],
        },
        {
          title: "Z-API Playground",
          href: "/admin/zapi/playground",
          items: [],
          disabled: false,
          tags: ["zapi", "teste", "whatsapp", "playground", "api"],
        },
        {
          title: "Z-API Webhook Logs",
          href: "/admin/zapi/logs",
          items: [],
          disabled: false,
          tags: ["zapi", "log", "webhook", "historico", "eventos"],
        },
      ],
    },
    {
      title: "CRM",
      disabled: false,
      items: [
        {
          title: "Clientes",
          href: "/admin/crm",
          items: [],
          disabled: false,
          tags: ["cliente", "cadastro", "comprador", "historico", "contato"],
        },
        {
          title: "Relatório de inserções",
          href: "/admin/crm/jornada-de-inserimento",
          items: [],
          disabled: false,
          tags: ["insercao", "jornada", "relatorio", "cliente", "novo"],
        },
        {
          title: "Campanhas",
          href: "/admin/crm/campaigns",
          items: [],
          disabled: false,
          tags: ["campanha", "marketing", "comunicacao", "crm", "email"],
        },
      ],
    },
    {
      title: "Marketing",
      disabled: false,
      items: [
        {
          title: "Reservas de pizza",
          href: "/admin/marketing/reservas-pizza",
          items: [],
          disabled: false,
          tags: ["reserva", "pizza", "campanha", "marketing", "bairro"],
        },
        {
          title: "Notificações (Push)",
          href: "/admin/push-notifications",
          items: [],
          disabled: false,
          tags: ["push", "notificacao", "mobile", "app", "alerta"],
        },
        {
          title: "Pixel Facebook",
          href: "/admin/marketing/facebook-pixel",
          items: [],
          disabled: false,
          tags: ["pixel", "facebook", "ads", "tracking", "meta"],
        },
        {
          title: "Whatsapp Status",
          href: "/admin/marketing/whatsapp-status",
          items: [],
          disabled: false,
          tags: ["whatsapp", "status", "marketing", "story", "divulgacao"],
        },
      ],
    },
  ],
};

export default ADMIN_NAVIGATION_LINKS;
