const AUTH_COOKIE_SECRET =
  process.env.AUTH_COOKIE_SECRET ||
  process.env.USER_AUTH_COOKIE_SECRET ||
  process.env.GOOGLE_AUTH_COOKIE_SECRET;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GOOGLE_CALLBACK_URL = process.env.GOOGLE_CALLBACK_URL;

export {
  AUTH_COOKIE_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL,
};
