import { MogoBaseOrder, MogoHttpClientInterface } from "./types";

export default class MogoHttpClientMock implements MogoHttpClientInterface {
  async getOrdersOpened() {
    const orders: MogoBaseOrder[] = [
      {
        Id: 729,
        NumeroPedido: "000729",
        Itens: [
          {
            IdProduto: 18,
            IdItemPedido: 0,
            Descricao: "Pizza Tamanho Médio",
            Observacao: "(Tamanho Romana Média)",
            Quantidade: 1.0,
            ValorUnitario: 119.9,
            Adicionais: [],
            Sabores: [
              { Descricao: "Mortazza", Quantidade: 1.0, Valor: 0.0 },
              { Descricao: "Portuguesa", Quantidade: 1.0, Valor: 0.0 },
            ],
          },
          {
            IdProduto: 151,
            IdItemPedido: 0,
            Descricao: "Taxa de Serviço",
            Observacao: null,
            Quantidade: 1.0,
            ValorUnitario: 0.87,
            Adicionais: [],
            Sabores: [],
          },
          {
            IdProduto: 20,
            IdItemPedido: 0,
            Descricao: "Taxa de entrega",
            Observacao: null,
            Quantidade: 1.0,
            ValorUnitario: 9.0,
            Adicionais: [],
            Sabores: [],
          },
        ],
        SubTotal: 120.77,
        TaxaEntrega: 9.0,
        DataPedido: "04/01/2024 00:00:00",
        HoraPedido: "20:50:50",
        HoraEntrega: null,
        HoraAcerto: "",
        FormaPagamento: "Aiqfome Online",
        TrocoDelivery: 0.0,
        Logradouro: "Rua Itacolomi",
        Numero: "1900",
        Bairro: "Amadori",
        Cidade: "Pato Branco",
        UF: "PR",
        ReaisDesconto: 0.0,
        PercentualDesconto: 0.0,
        StatusPedido: 0,
        StatusEntrega: 0,
        HoraEntregaTxt: "22:50:13",
        DataEntregaTxt: null,
        CodObsEntrega: 0,
        DataSaidaEntregador: null,
        Adiantamentos: null,
        IdPedRemoteDevice: "96610659",
        ObsEntrega: "ver que no último pedido meu não veio uma coca de 600ml",
        Vendedor: null,
        Cliente: "Carlos Rafael Manfredini",
        IdCliente: 381,
        IdEntregador: 0,
        Latitude: "",
        Longitude: "",
        ReferenceIFood: null,
        PickupCode: null,
      },
      {
        Id: 728,
        NumeroPedido: "000728",
        Itens: [
          {
            IdProduto: 18,
            IdItemPedido: 0,
            Descricao: "Pizza Tamanho Médio",
            Observacao: "(Tamanho Romana Média)",
            Quantidade: 1.0,
            ValorUnitario: 89.9,
            Adicionais: [],
            Sabores: [
              { Descricao: "Margherita", Quantidade: 1.0, Valor: 0.0 },
              {
                Descricao: "Frango e Catupiry",
                Quantidade: 1.0,
                Valor: 0.0,
              },
            ],
          },
          {
            IdProduto: 58,
            IdItemPedido: 0,
            Descricao: "Coca Cola Lata 350 ml",
            Observacao: "(Tamanho Único)",
            Quantidade: 1.0,
            ValorUnitario: 4.5,
            Adicionais: [],
            Sabores: [],
          },
          {
            IdProduto: 151,
            IdItemPedido: 0,
            Descricao: "Taxa de Serviço",
            Observacao: null,
            Quantidade: 1.0,
            ValorUnitario: 1.0,
            Adicionais: [],
            Sabores: [],
          },
          {
            IdProduto: 20,
            IdItemPedido: 0,
            Descricao: "Taxa de entrega",
            Observacao: null,
            Quantidade: 1.0,
            ValorUnitario: 8.0,
            Adicionais: [],
            Sabores: [],
          },
        ],
        SubTotal: 95.4,
        TaxaEntrega: 8.0,
        DataPedido: "03/01/2024 00:00:00",
        HoraPedido: "19:32:28",
        HoraEntrega: null,
        HoraAcerto: "",
        FormaPagamento: "Cartão Débito",
        TrocoDelivery: 0.0,
        Logradouro: "Rua José Picolo",
        Numero: "137",
        Bairro: "La Salle",
        Cidade: "Pato Branco",
        UF: "PR",
        ReaisDesconto: 0.0,
        PercentualDesconto: 0.0,
        StatusPedido: 0,
        StatusEntrega: 0,
        HoraEntregaTxt: "21:32:16",
        DataEntregaTxt: null,
        CodObsEntrega: 0,
        DataSaidaEntregador: null,
        Adiantamentos: null,
        IdPedRemoteDevice: "96556797",
        ObsEntrega: "",
        Vendedor: null,
        Cliente: "Clovis Padoan Filho",
        IdCliente: 92,
        IdEntregador: 0,
        Latitude: "",
        Longitude: "",
        ReferenceIFood: null,
        PickupCode: null,
      },
      {
        Id: 727,
        NumeroPedido: "000727",
        Itens: [
          {
            IdProduto: 18,
            IdItemPedido: 0,
            Descricao: "Pizza Tamanho Médio",
            Observacao: "",
            Quantidade: 1.0,
            ValorUnitario: 89.9,
            Adicionais: [],
            Sabores: [
              { Descricao: "Affumicata", Quantidade: 1.0, Valor: 89.9 },
            ],
          },
        ],
        SubTotal: 89.9,
        TaxaEntrega: 0.0,
        DataPedido: "02/01/2024 00:00:00",
        HoraPedido: "12:17:33",
        HoraEntrega: "12:18",
        HoraAcerto: "",
        FormaPagamento: "Dinheiro",
        TrocoDelivery: 0.0,
        Logradouro: "",
        Numero: "",
        Bairro: "",
        Cidade: "",
        UF: "",
        ReaisDesconto: 0.0,
        PercentualDesconto: 0.0,
        StatusPedido: 0,
        StatusEntrega: 0,
        HoraEntregaTxt: "12:18:49",
        DataEntregaTxt: null,
        CodObsEntrega: 1,
        DataSaidaEntregador: "02/01/2024",
        Adiantamentos: null,
        IdPedRemoteDevice: "638398054210590000",
        ObsEntrega: null,
        Vendedor: null,
        Cliente: "Nicola Lanzoni",
        IdCliente: 535,
        IdEntregador: 0,
        Latitude: "",
        Longitude: "",
        ReferenceIFood: null,
        PickupCode: null,
      },
    ];

    return new Promise<MogoBaseOrder[]>((resolve) => {
      resolve(orders);
    });
  }
}
